name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: ./.github/workflows/deploy.sh
